name: java_tests
on:
  pull_request:
  push:
  #  branches: [master]
jobs:
  java_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]  # , macos-latest
        java: [8, 11, 14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: |
           java -version
           ant developer-build
           ant regrtest-travis
